name: .NET Core

on: 
  release:
    types:
      [released]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build Kapitan with dotnet
      run: dotnet build --configuration Release src/Kapitan.sln
    - name: Package Kapitan
      run: dotnet pack --configuration Release src/Kapitan.sln -o ../artifacts/
    - name: Publish All
      run: |
           for f in ../artifacts/*.nupkg
           do
             dotnet nuget push $f -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json
           done
      shell: bash
      env:
        NUGET_TOKEN: ${{ secrets.NuGetKey }}
